"""Generate exportable CSV reports and markdown executive summaries."""

from __future__ import annotations

from datetime import datetime
from pathlib import Path

import pandas as pd

from src.schemas import ExecutiveSummary

OUTPUT_DIR = Path("output")


def generate_retention_csv(scored_df: pd.DataFrame, filepath: Path | None = None) -> Path:
    """
    Export a prioritized retention list CSV containing scored customers
    with their risk factors and (if generated) LLM explanations.
    """
    OUTPUT_DIR.mkdir(parents=True, exist_ok=True)

    if filepath is None:
        ts = datetime.now().strftime("%Y%m%d_%H%M%S")
        filepath = OUTPUT_DIR / f"retention_list_{ts}.csv"

    export_cols = [
        "customer_id",
        "customer_name",
        "segment",
        "revenue_tier",
        "monthly_revenue",
        "account_owner",
        "churn_probability",
        "risk_tier",
        "contract_months_remaining",
        "support_tickets_90d",
        "product_usage_score",
        "days_since_login",
        "nps_score",
        "payment_delays",
    ]

    # Add explainability columns if present
    if "top_risk_factors" in scored_df.columns:
        export_cols.append("top_risk_factors")

    # Add LLM columns if present
    for col in ["ai_explanation", "ai_retention_action", "ai_urgency", "ai_talking_points"]:
        if col in scored_df.columns:
            export_cols.append(col)

    out = scored_df[[c for c in export_cols if c in scored_df.columns]].copy()

    # Flatten list columns for CSV
    if "top_risk_factors" in out.columns:
        out["top_risk_factors"] = out["top_risk_factors"].apply(
            lambda x: " | ".join(x) if isinstance(x, list) else x
        )
    if "ai_talking_points" in out.columns:
        out["ai_talking_points"] = out["ai_talking_points"].apply(
            lambda x: " | ".join(x) if isinstance(x, list) else x
        )

    out["churn_probability"] = out["churn_probability"].map("{:.1%}".format)
    out.to_csv(filepath, index=False)
    return filepath


def generate_executive_report(summary: ExecutiveSummary, filepath: Path | None = None) -> Path:
    """
    Write a markdown-formatted executive summary report to disk.
    Returns the path to the written file.
    """
    OUTPUT_DIR.mkdir(parents=True, exist_ok=True)

    if filepath is None:
        ts = datetime.now().strftime("%Y%m%d_%H%M%S")
        filepath = OUTPUT_DIR / f"executive_summary_{ts}.md"

    now = datetime.now().strftime("%B %d, %Y %H:%M")

    lines = [
        "# Churn Early Warning — Executive Summary",
        f"*Generated: {now}*",
        "",
        "---",
        "",
        "## Portfolio Overview",
        "",
        f"| Metric | Value |",
        f"|--------|-------|",
        f"| Total Customers Analyzed | {summary.total_customers_analyzed} |",
        f"| Critical Risk | {summary.critical_risk_count} |",
        f"| High Risk | {summary.high_risk_count} |",
        f"| Total At-Risk MRR | ${summary.total_at_risk_mrr:,.0f} |",
        "",
        "---",
        "",
        "## Executive Narrative",
        "",
        summary.summary_narrative,
        "",
        "---",
        "",
        "## Top Segments at Risk",
        "",
    ]
    for seg in summary.top_segments_at_risk:
        lines.append(f"- {seg}")

    lines += [
        "",
        "---",
        "",
        "## Recommended Priorities",
        "",
    ]
    for i, priority in enumerate(summary.recommended_priorities, 1):
        lines.append(f"{i}. {priority}")

    lines += [
        "",
        "---",
        "",
        "*Report generated by AI Churn Early Warning System*",
    ]

    filepath.write_text("\n".join(lines), encoding="utf-8")
    return filepath


def flatten_llm_columns(scored_df: pd.DataFrame) -> pd.DataFrame:
    """
    If scored_df has an 'explanation' column (ChurnExplanation objects),
    flatten it into individual string columns for export and display.
    """
    if "explanation" not in scored_df.columns:
        return scored_df

    df = scored_df.copy()

    def _safe_get(explanation, attr, default=""):
        if explanation is None:
            return default
        val = getattr(explanation, attr, default)
        if isinstance(val, list):
            return " | ".join(val)
        return val or default

    df["ai_explanation"] = df["explanation"].apply(lambda e: _safe_get(e, "plain_english_explanation"))
    df["ai_retention_action"] = df["explanation"].apply(lambda e: _safe_get(e, "retention_action"))
    df["ai_urgency"] = df["explanation"].apply(lambda e: _safe_get(e, "urgency_level"))
    df["ai_talking_points"] = df["explanation"].apply(
        lambda e: getattr(e, "talking_points", []) if e else []
    )
    return df
